@startuml
title افزودن یادآور
autonumber
actor کاربر
control رابط_کاربری
کاربر -> رابط_کاربری : درخواست افزودن یادآور
رابط_کاربری -> کاربر : نمایش فرم افزودن یادآور
کاربر -> رابط_کاربری : کامل کردن فرم

database دیتابیس
رابط_کاربری -> دیتابیس : ذخیره یادآور
رابط_کاربری -> سیستم_یادآور : ثبت یاد آور بعدی
سیستم_یادآور -> اندروید : افزودن یادآور
سیستم_یادآور -> رابط_کاربری : تایید ثبت
رابط_کاربری -> کاربر : نمایش ثبت شده

newpage باز کردن نرم افزار
کاربر -> رابط_کاربری : کلیک بر آیکون برنامه
رابط_کاربری -> دیتابیس : درخواست یادآور ها
دیتابیس -> رابط_کاربری : ارسال یادآور ها
رابط_کاربری -> کاربر : نمایش صفحه اصلی (لیست یادآور ها)


newpage باز کردن نرم افزار



newpage باز کردن نرم افزار



newpage باز کردن نرم افزار



newpage باز کردن نرم افزار



newpage باز کردن نرم افزار



newpage باز کردن نرم افزار

@enduml